id: P3FB309B8
initial_creation_type: input
source_metadata:
  title: Paksam Wangpo Series
  language: en
  description: 'Texts by and about Paksam Wangpo (dpag bsam dbang po, 1593–1641),
    the Fifth Drukchen:'
  volume:
    b8b7cfb0d88b4a28a20ffe23790be5db:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
created_at: '2022-03-01T01:09:54.708232'
last_modified_at: '2022-03-01T01:09:54.708238'
